get:
  tags:
    - Product
  summary: Get a List of products.
  description: Get a List of products.
  operationId: listProducts
  responses:
    "200":
      description: "Success"
      content:
        application/json:
          schema:
            $ref: "../../components/schemas/v1/product_list.yaml"
    "404":
      description: Not found
      content:
        application/json:
          schema:
            $ref: "../../components/schemas/Problem.yaml"
  security:
    - basic_auth: []
